name: Tailadmin Laravel Deployment
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Env
        run: |
          cp .env.example .env
          sed -i 's/DB_HOST=127.0.0.1/DB_HOST=mysql_db/' .env
          sed -i 's/DB_DATABASE=laravel/DB_DATABASE=tailadmin/' .env
          sed -i 's/DB_USERNAME=root/DB_USERNAME=user/' .env
          sed -i 's/DB_PASSWORD=/DB_PASSWORD=password/' .env

      - name: Cleanup & Build Image
        run: |
          docker system prune -f
          docker build -t farah1504_docker-tailadmin-laravel:beta .

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Push Image
        run: docker push farah1504_docker-tailadmin-laravel:beta

      - name: Run Containers
        run: |
          docker rm -f app_tailadmin mysql_db || true
          
          # Jalankan Database
          docker run -d --name mysql_db \
            -e MYSQL_DATABASE=tailadmin \
            -e MYSQL_USER=user \
            -e MYSQL_PASSWORD=password \
            -e MYSQL_ROOT_PASSWORD=root \
            --network bridge mysql:8.0

          # Jalankan Aplikasi Laravel di Port 8090
          docker run -d --name app_tailadmin \
            -p 8090:8000 \
            --link mysql_db:mysql_db \
            --network bridge \
            farah1504_docker-tailadmin-laravel:beta php artisan serve --host=0.0.0.0

      - name: Finalize Laravel
        run: |
          sleep 20
          docker exec app_tailadmin php artisan key:generate
          docker exec app_tailadmin php artisan migrate --seed --force
          docker exec app_tailadmin php artisan storage:link
